---
- name: '[RHEL8] add Postgres repo and install'
  block:
    - dnf:
        name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
        state: present
        update_cache: yes
        disable_gpg_check: yes
    - shell:
        cmd: dnf -qy module disable postgresql
    - dnf:
        name:
          - postgresql{{ version }}-server
          - postgresql{{ version }}-contrib
        state: present
        update_cache: yes
        disable_gpg_check: yes
  when:
     - ansible_distribution_file_variety == 'RedHat'
     - ansible_distribution_major_version == '8'

- name: '[RHEL7] add Postgres repo and install'
  block:
    - yum:
        name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
        state: present
        update_cache: yes
        disable_gpg_check: yes
        validate_certs: no
    - yum:
        name:
          - postgresql{{ version }}-server
          - postgresql{{ version }}-contrib
        state: present
        update_cache: yes
        disable_gpg_check: yes
  when:
    - ansible_distribution_file_variety == 'RedHat'
    - ansible_distribution_major_version == '7'

- name: '[Debian/Ubuntu] add Postgres repo and install'
  block:
    - shell:
        cmd: |
          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list &&
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - apt:
        name:
          - postgresql-{{ version }}
          - postgresql-contrib-{{ version }}
        state: present
        update_cache: yes
    - systemd:
       name: postgresql
       state: stopped
       enabled: no
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: 'create user postgres_exporter'
  user:
    name: postgres_exporter
    password: "{{ 'exporter' | password_hash('sha512') }}"

- name: 'download Postgres Exporter and extract tar.gz'
  unarchive:
    src: 'https://github.com/prometheus-community/postgres_exporter/releases/download/v0.10.0/postgres_exporter-0.10.0.linux-amd64.tar.gz'
    dest: /tmp
    remote_src: yes

- name: 'move binary'
  copy:
    src: /tmp/postgres_exporter-0.10.0.linux-amd64/postgres_exporter
    dest: /usr/local/bin/
    owner: postgres_exporter
    group: postgres_exporter
    mode: '0700'
    remote_src: true

- name: 'create service file'
  template:
    src: monitoring/postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
  notify: restart-postgres_exporter
